In [2]:
import numpy

## 1. Heads or Tails

In [29]:
if (numpy.random.random() > .5):
    print('Heads')
else:
    print('Tails')

Tails


In [32]:
numpy.random.random((4,4))

array([[0.0294833 , 0.27878514, 0.88743872, 0.02207309],
       [0.84253803, 0.57131543, 0.95733409, 0.27328405],
       [0.80705073, 0.68915091, 0.42852301, 0.37047637],
       [0.62677833, 0.47275035, 0.55579602, 0.24836134]])

In [37]:
numpy.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [41]:
numpy.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [43]:
import numpy as np

## 2. Array Reshaping

In [48]:
arr = np.random.random((4,4))

In [51]:
arr

array([[0.6017092 , 0.76785525, 0.87018904, 0.67142869],
       [0.84206681, 0.5136036 , 0.55161647, 0.824409  ],
       [0.18630646, 0.7433512 , 0.65180343, 0.29632239],
       [0.89641309, 0.84341171, 0.84782499, 0.22962338]])

In [53]:
arr.shape

(4, 4)

In [57]:
arr = np.reshape(arr, (2,8))

In [58]:
arr.shape

(2, 8)

In [59]:
arr

array([[0.6017092 , 0.76785525, 0.87018904, 0.67142869, 0.84206681,
        0.5136036 , 0.55161647, 0.824409  ],
       [0.18630646, 0.7433512 , 0.65180343, 0.29632239, 0.89641309,
        0.84341171, 0.84782499, 0.22962338]])

In [61]:
arr = arr.reshape((1,16))

In [62]:
arr.shape

(1, 16)

In [71]:
arr = np.random.random((5,5))

In [76]:
arr.shape

(5, 5)

## 3. Array Flatten

In [77]:
arr = arr.flatten()

In [78]:
arr.shape

(25,)

## 4. Array to list & Vice Versa

In [79]:
lst = [1,2,3,4,5]

In [81]:
arr = np.array(lst)

In [82]:
arr

array([1, 2, 3, 4, 5])

In [85]:
lst = list(arr)

In [86]:
arr

array([1, 2, 3, 4, 5])

In [87]:
lst

[1, 2, 3, 4, 5]

In [99]:
arr

array([1, 2, 3, 4, 5])

## 5. Arithematic Operations on Arrays

In [102]:
print(arr + 1)
print(arr - 1)
print(arr * 2)
print(arr / 2)
print(arr ** 2)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [107]:
arr

array([1, 2, 3, 4, 5])

In [108]:
arr += 5

In [110]:
arr *= 2

In [111]:
arr

array([12, 14, 16, 18, 20])

In [112]:
arr.min()

12

In [113]:
arr.max()

20

In [114]:
arr.mean()

16.0

## 6. Operations on Arrays (Row & Column Wise)

In [117]:
arr1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])

In [121]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [122]:
arr1.max()

6

In [123]:
arr1.max(axis = 0)       # Column-wise Maximum

array([2, 3, 4, 5, 6])

In [124]:
arr1.max(axis = 1)       # Row-wise Maximum

array([5, 6])

In [126]:
arr1.min(axis = 0)       # Column-wise Maximum

array([1, 2, 3, 4, 5])

In [127]:
arr1.min(axis = 1)

array([1, 2])

In [128]:
arr1.sum()

35

In [129]:
arr1.sum(axis = 0)

array([ 3,  5,  7,  9, 11])

In [130]:
arr1.sum(axis = 1)

array([15, 20])

## 7. Arithematic Operations on Multiple Arrays

In [131]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[3,4,5],[6,7,8]])
arr3 = np.array([[6,5,4],[3,2,1]])

In [132]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
arr2

array([[3, 4, 5],
       [6, 7, 8]])

In [134]:
arr3

array([[6, 5, 4],
       [3, 2, 1]])

In [135]:
arr1 + arr2

array([[ 4,  6,  8],
       [10, 12, 14]])

In [136]:
arr1 - arr2

array([[-2, -2, -2],
       [-2, -2, -2]])

In [137]:
arr1 * arr2

array([[ 3,  8, 15],
       [24, 35, 48]])

In [138]:
arr1 + arr2 + arr3

array([[10, 11, 12],
       [13, 14, 15]])

## 8. Array Slicing

In [141]:
arr1 = np.array([1,2,3,4,5,6,7])

In [142]:
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [147]:
arr1[3]

4

In [150]:
arr1[-4]

4

In [151]:
arr1[ : ]

array([1, 2, 3, 4, 5, 6, 7])

In [152]:
arr1[1 : -1]

array([2, 3, 4, 5, 6])

## 9. Array Sorting

In [153]:
arr1 = np.array([6,5,4,7,8,9])

In [154]:
arr1

array([6, 5, 4, 7, 8, 9])

In [156]:
np.sort(arr1)

array([4, 5, 6, 7, 8, 9])

In [158]:
np.sort(arr1, kind = 'quicksort')

array([4, 5, 6, 7, 8, 9])

In [161]:
arr1 = np.array([[3,6,1],[2,4,6]])

In [162]:
arr1

array([[3, 6, 1],
       [2, 4, 6]])

In [164]:
np.sort(arr1, axis = 0)   # Column-wise Sorting

array([[2, 4, 1],
       [3, 6, 6]])

In [166]:
np.sort(arr1, axis = 1)     # Row-wise Sorting

array([[1, 3, 6],
       [2, 4, 6]])

## 10. Array Merging

In [167]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,5,6],[7,8,9]])

In [168]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
arr2

array([[4, 5, 6],
       [7, 8, 9]])

In [181]:
arr_h =  np.hstack((arr1,arr2))          # Horizontal Stack

In [182]:
arr_v = np.vstack((arr1,arr2))          # Vertical Stack

In [178]:
np.concatenate((arr1,arr2), axis = 1)        # 1 - Horizontal Stack

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [179]:
np.concatenate((arr1,arr2), axis = 0)        # 0 - Vertical Stack

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

## 11. Array Spliting

In [183]:
arr_h

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [184]:
arr_v

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
np.hsplit(arr_h, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[4, 5, 6],
        [7, 8, 9]])]

In [193]:
np.vsplit(arr_v, 4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]])]

## 12. Advance Numpy over Lists

In [195]:
lst = [43,23,54,22,10,12,18]

In [198]:
c = 0

for i in lst:
    if (i >= 18):
        c += 1
        
print("Eligible : ", c)

Eligible :  5


In [199]:
arr = np.array([43,23,54,22,10,12,18])

In [200]:
arr

array([43, 23, 54, 22, 10, 12, 18])

In [204]:
arr >= 18

array([ True,  True,  True,  True, False, False,  True])

## 12.1) How many people are eligible for voting?

In [207]:
len(arr[arr >= 18])

5

## 12.2) How many people have even age?

In [210]:
len(arr[arr % 2 == 0])

5