In [83]:
import numpy as np
import pandas as pd

df = pd.read_csv('imdb.csv')
df.head()

Poster_Link  \
0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   
3  https://m.media-amazon.com/images/M/MV5BMWMwMG...   
4  https://m.media-amazon.com/images/M/MV5BMWU4N2...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   
3    The Godfather: Part II          1974           A  202 min   
4              12 Angry Men          1957           U   96 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   
3          Crime, Drama          9.0   
4          Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   
3  The early life and career of Vito Corleone in ...        90.0   
4  A jury holdout attempts to prevent a miscarria...        96.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   
3  Francis Ford Coppola       Al Pacino  Robert De Niro  Robert Duvall   
4          Sidney Lumet     Henry Fonda     Lee J. Cobb  Martin Balsam   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444  
3    Diane Keaton      1129952   57,300,000  
4    John Fiedler       689845    4,360,000

#### 1.1) Removing Columns that are of no use

In [84]:
del df['Poster_Link']
del df['Released_Year']
del df['Certificate']
del df['Runtime']
del df['Overview']
del df['Meta_score']
del df['Director']
del df['Star1']
del df['Star2']
del df['Star3']
del df['Star4']
del df['No_of_Votes']
del df['Gross']
del df['IMDB_Rating']

df.head()

Series_Title                 Genre
0  The Shawshank Redemption                 Drama
1             The Godfather          Crime, Drama
2           The Dark Knight  Action, Crime, Drama
3    The Godfather: Part II          Crime, Drama
4              12 Angry Men          Crime, Drama

#### 1.2) Checking Null Values

In [85]:
df.isnull().sum()

Series_Title    0
Genre           0
dtype: int64

#### 1.3) Finding All Genre

In [86]:
genre = []
for i in df['Genre']:
    
    genre += i.split(',')
    
genre = [i.strip() for i in genre]    
genre = list(set(genre))

#### 1.4) One Hot Conversion

In [87]:
one_hot = []

for i in df['Genre']:
    
    i = [j.strip() for j in i.split(',')]        # Removing Spaces
    enc = [0 for i in range(21)]
    
    for gen in i:
        enc[genre.index(gen)] = 1
    
    one_hot.append(enc)

#### 1.5) One Hot Conversion Verification (Counting Number of Genres and 1's)

In [88]:
for i in range(len(df['Genre'])):
    
    x1 = len(df['Genre'][i].split(','))          # Finding Number of Genres in the Movie
    x2 = list(one_hot[i]).count(1)               # Finding Number of 1's in One Hot List
    
    if (x1 != x2):
        print('Not Equal')

#### 1.6) Converting OneHot to Array

In [89]:
one_hot = np.array(one_hot)

one_hot.shape

(1000, 21)

#### 1.7) Adding OneHotData Data to DataFrame

In [108]:
for i in range(21):
    df[genre[i]] = one_hot[ : ,i]
    
df.head()

Series_Title                 Genre  Crime  Fantasy  Adventure  \
0  The Shawshank Redemption                 Drama      0        0          0   
1             The Godfather          Crime, Drama      1        0          0   
2           The Dark Knight  Action, Crime, Drama      1        0          0   
3    The Godfather: Part II          Crime, Drama      1        0          0   
4              12 Angry Men          Crime, Drama      1        0          0   

   Sport  Action  Musical  Drama  Film-Noir  ...  Comedy  Western  Biography  \
0      0       0        0      1          0  ...       0        0          0   
1      0       0        0      1          0  ...       0        0          0   
2      0       1        0      1          0  ...       0        0          0   
3      0       0        0      1          0  ...       0        0          0   
4      0       0        0      1          0  ...       0        0          0   

   War  Romance  Animation  Family  Sci-Fi  Horror  Thriller  
0    0        0          0       0       0       0         0  
1    0        0          0       0       0       0         0  
2    0        0          0       0       0       0         0  
3    0        0          0       0       0       0         0  
4    0        0          0       0       0       0         0  

[5 rows x 23 columns]

## Prediction

#### 2.1) With Exact Genre

In [146]:
user = df[df['Series_Title'] == 'Lifeboat'].values[0][2:]

In [149]:
for i in df.values:
    if(list(user - i[2:]).count(0) == 21):
        print(i[0])

Saving Private Ryan
Paths of Glory
Full Metal Jacket
Mandariinid
Judgment at Nuremberg
Platoon
The Deer Hunter
La battaglia di Algeri
Ivanovo detstvo
La Grande Illusion
Au revoir les enfants
All Quiet on the Western Front
Beasts of No Nation
The Thin Red Line
Lifeboat


In [143]:
df

Series_Title                     Genre  Crime  Fantasy  \
0    The Shawshank Redemption                     Drama      0        0   
1               The Godfather              Crime, Drama      1        0   
2             The Dark Knight      Action, Crime, Drama      1        0   
3      The Godfather: Part II              Crime, Drama      1        0   
4                12 Angry Men              Crime, Drama      1        0   
..                        ...                       ...    ...      ...   
995    Breakfast at Tiffany's    Comedy, Drama, Romance      0        0   
996                     Giant            Drama, Western      0        0   
997     From Here to Eternity       Drama, Romance, War      0        0   
998                  Lifeboat                Drama, War      0        0   
999              The 39 Steps  Crime, Mystery, Thriller      1        0   

     Adventure  Sport  Action  Musical  Drama  Film-Noir  ...  Comedy  \
0            0      0       0        0      1          0  ...       0   
1            0      0       0        0      1          0  ...       0   
2            0      0       1        0      1          0  ...       0   
3            0      0       0        0      1          0  ...       0   
4            0      0       0        0      1          0  ...       0   
..         ...    ...     ...      ...    ...        ...  ...     ...   
995          0      0       0        0      1          0  ...       1   
996          0      0       0        0      1          0  ...       0   
997          0      0       0        0      1          0  ...       0   
998          0      0       0        0      1          0  ...       0   
999          0      0       0        0      0          0  ...       0   

     Western  Biography  War  Romance  Animation  Family  Sci-Fi  Horror  \
0          0          0    0        0          0       0       0       0   
1          0          0    0        0          0       0       0       0   
2          0          0    0        0          0       0       0       0   
3          0          0    0        0          0       0       0       0   
4          0          0    0        0          0       0       0       0   
..       ...        ...  ...      ...        ...     ...     ...     ...   
995        0          0    0        1          0       0       0       0   
996        1          0    0        0          0       0       0       0   
997        0          0    1        1          0       0       0       0   
998        0          0    1        0          0       0       0       0   
999        0          0    0        0          0       0       0       0   

     Thriller  
0           0  
1           0  
2           0  
3           0  
4           0  
..        ...  
995         0  
996         0  
997         0  
998         0  
999         1  

[1000 rows x 23 columns]

In [150]:
m2 - m

array([-1,  1,  0])

In [123]:
[0,0,0,0,1]
[0,1,0,0,1]

array([-1,  0,  1])

In [124]:
m4 - m

array([0, 0, 0])

In [ ]:
m2 - m